/**
 * Créditos das fotos — **gerado** por `npm run photos:prepare`. Não edite à mão.
 *
 * CC BY exige crédito visível ao autor. Esta lista não é cortesia: é condição de uso das
 * fotos que o app embarca, e alimenta a tela de créditos.
 */

export interface CreditoFoto {
  especie: string;
  autor: string;
  licenca: string;
  pagina: string;
}

export const CREDITOS: CreditoFoto[] = [
  { especie: 'Abrótea', autor: 'Nicolas Olejnik, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/7300102' },
  { especie: 'Anchova', autor: 'Jason E. Farabaugh, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/54875404' },
  { especie: 'Bagre-africano', autor: 'Shaunak Modi, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/30939711' },
  { especie: 'Bagre-amarelo', autor: 'Sebastián Fornés, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/104612007' },
  { especie: 'Bagre-americano', autor: 'Joshua Johnson, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/263703713' },
  { especie: 'Bagre-branco', autor: 'no rights reserved', licenca: 'CC0', pagina: 'https://www.inaturalist.org/observations/105663230' },
  { especie: 'Baiacu', autor: 'Jean Martins, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/195689619' },
  { especie: 'Birú', autor: 'RAP, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/156411291' },
  { especie: 'Black bass', autor: 'Nick Tobler (Cowturtle), some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/190142449' },
  { especie: 'Cabrinha', autor: 'Gabriel Martínez, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/240733181' },
  { especie: 'Cação-anjo', autor: 'no rights reserved', licenca: 'CC0', pagina: 'https://www.inaturalist.org/observations/161352203' },
  { especie: 'Cação-bico-de-cristal', autor: 'Zara, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/152329626' },
  { especie: 'Cação-bico-doce', autor: 'D Ross Robertson', licenca: 'Public domain', pagina: 'https://commons.wikimedia.org/wiki/File%3ARhizoprionodon%20lalandii%20head.jpg' },
  { especie: 'Cachara', autor: 'Pablo Scarabotti, Tzipe Govezensky, Pablo Bolcatto &amp; Rafael A. Barrio', licenca: 'CC BY 4.0', pagina: 'https://commons.wikimedia.org/wiki/File%3APseudoplatystoma%20duo%20duo.png' },
  { especie: 'Caçonete', autor: 'Ezequiel Vera, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/125106460' },
  { especie: 'Cará', autor: 'Yung-Lun Lin, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/171901211' },
  { especie: 'Cará-do-rabo-amarelo', autor: 'no rights reserved', licenca: 'CC0', pagina: 'https://www.inaturalist.org/observations/105881021' },
  { especie: 'Carpa-cabeça-grande', autor: 'Jeffrey Lee (he/him/his), some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/9261095' },
  { especie: 'Carpa-capim', autor: 'Tyler Bishop, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/27579107' },
  { especie: 'Carpa-colorida', autor: 'Bernard Spragg. NZ from Christchurch, New Zealand', licenca: 'CC0', pagina: 'https://commons.wikimedia.org/wiki/File%3AKoi%20Carp.%20(9962457875).jpg' },
  { especie: 'Carpa-espelho', autor: 'USFWS Mountain Prairie', licenca: 'Public domain', pagina: 'https://commons.wikimedia.org/wiki/File%3A%22Mirror%20Carp%22%20(Cyprinus%20carpio)%20(51022632707).jpg' },
  { especie: 'Carpa-húngara', autor: 'りなべる, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/69124740' },
  { especie: 'Carpa-prateada', autor: 'Bob Virag, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/57797084' },
  { especie: 'Cascudo', autor: 'facundo cortondo, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/197429461' },
  { especie: 'Castanha', autor: 'no rights reserved', licenca: 'CC0', pagina: 'https://www.inaturalist.org/observations/261306928' },
  { especie: 'Chanchito', autor: 'Pablo H Capovilla, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/183339665' },
  { especie: 'Chicharro', autor: 'no rights reserved', licenca: 'CC0', pagina: 'https://www.inaturalist.org/observations/53498677' },
  { especie: 'Congro', autor: 'no rights reserved', licenca: 'CC0', pagina: 'https://www.inaturalist.org/observations/163749301' },
  { especie: 'Corvina', autor: 'Diogo Luiz, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/138306975' },
  { especie: 'Dourado', autor: 'Diego Carús', licenca: 'CC0', pagina: 'https://commons.wikimedia.org/wiki/File%3ASalminus%20brasiliensis%20102879277.jpg' },
  { especie: 'Esturjão', autor: 'Oleksii Vasyliuk, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/59175015' },
  { especie: 'Grumatã', autor: 'Nicolas Olejnik, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/1552028' },
  { especie: 'Guaivira', autor: 'Fernando Mistrorigo de Almeida', licenca: 'CC BY 3.0', pagina: 'https://commons.wikimedia.org/wiki/File%3AOligoplites%20saliens.png' },
  { especie: 'Joaninha', autor: 'Donald Davesne, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/322937090' },
  { especie: 'Jundiá', autor: 'James-LaFontaine, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/259042631' },
  { especie: 'Kinguio', autor: 'Mohammad Amin Ghaffari, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/79771238' },
  { especie: 'Lambari', autor: 'Rocío Esmeralda Pose, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/196169492' },
  { especie: 'Lambari-cachorro', autor: 'Tomás Carranza Perales, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/105468447' },
  { especie: 'Lambari-do-rabo-vermelho', autor: 'Zakqary Roy, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/260210185' },
  { especie: 'Linguado', autor: 'Malena Lorente, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/312018199' },
  { especie: 'Mandi-amarelo', autor: 'João D\'Andretta, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/66665270' },
  { especie: 'Maria-luiza', autor: 'no rights reserved', licenca: 'CC0', pagina: 'https://www.inaturalist.org/observations/198934902' },
  { especie: 'Marimbá', autor: 'Donald Davesne, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/385780106' },
  { especie: 'Miraguaia', autor: 'Nicolas Olejnik, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/3733251' },
  { especie: 'Muçum', autor: 'Rocío Esmeralda Pose, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/297927822' },
  { especie: 'Pacu', autor: 'Nicolas Olejnik, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/176627958' },
  { especie: 'Pampo-do-sul', autor: 'vinicius_s_domingues, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/117852721' },
  { especie: 'Papa-terra', autor: 'no rights reserved', licenca: 'CC0', pagina: 'https://www.inaturalist.org/observations/164413334' },
  { especie: 'Papa-terra-listrado', autor: 'Quinn, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/257065123' },
  { especie: 'Parati', autor: 'Scott Cave, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/207675277' },
  { especie: 'Peixe-espada', autor: 'Karim Haddad, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/34427090' },
  { especie: 'Peixe-galo', autor: 'Pam Kleinsasser, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/35064816' },
  { especie: 'Peixe-rei-de-lagoa', autor: 'no rights reserved', licenca: 'CC0', pagina: 'https://www.inaturalist.org/observations/65170016' },
  { especie: 'Peixe-rei-marinho', autor: 'Martín Acosta Albarracín, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/191514670' },
  { especie: 'Pescada-branca', autor: 'no rights reserved', licenca: 'CC0', pagina: 'https://www.inaturalist.org/observations/121362876' },
  { especie: 'Pescada-olhuda', autor: 'RAP, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/390279083' },
  { especie: 'Pescadinha-real', autor: 'William G. Borges, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/149418863' },
  { especie: 'Piava', autor: 'no rights reserved', licenca: 'CC0', pagina: 'https://www.inaturalist.org/observations/79867529' },
  { especie: 'Pintachara', autor: 'Pablo Scarabotti, Tzipe Govezensky, Pablo Bolcatto &amp; Rafael A. Barrio', licenca: 'CC BY 4.0', pagina: 'https://commons.wikimedia.org/wiki/File%3APseudoplatystoma%20corruscans%20RIP.png' },
  { especie: 'Pintado', autor: 'Martín Acosta Albarracín, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/205576577' },
  { especie: 'Pirapitinga', autor: 'Jay Pruett, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/178112642' },
  { especie: 'Raia-emplastro', autor: 'tlaloc27, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/123754651' },
  { especie: 'Raia-manteiga', autor: 'Alejandro Puente Tapia, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/71270911' },
  { especie: 'Raia-viola', autor: 'no rights reserved', licenca: 'CC0', pagina: 'https://www.inaturalist.org/observations/35740311' },
  { especie: 'Robalo-flecha', autor: 'Jacob Weston, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/161233369' },
  { especie: 'Robalo-peva', autor: 'James-LaFontaine, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/185150497' },
  { especie: 'Savelha', autor: 'Internet Archive Book Images', licenca: 'No restrictions', pagina: 'https://commons.wikimedia.org/wiki/File%3AAmerican%20fisheries-%20a%20history%20of%20the%20menhaden%20(1880)%20(17934017739).jpg' },
  { especie: 'Sororoca', autor: 'no rights reserved', licenca: 'CC0', pagina: 'https://www.inaturalist.org/observations/383051378' },
  { especie: 'Tabarana', autor: 'Douglas Lopes, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/254154465' },
  { especie: 'Tainha', autor: 'Diogo Luiz, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/29802065' },
  { especie: 'Tambacu', autor: 'observação do iNaturalist, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/387099634' },
  { especie: 'Tambaqui', autor: 'no rights reserved', licenca: 'CC0', pagina: 'https://www.inaturalist.org/observations/121241577' },
  { especie: 'Tamboatá', autor: 'no rights reserved', licenca: 'CC0', pagina: 'https://www.inaturalist.org/observations/193489492' },
  { especie: 'Tilápia', autor: 'renjus box, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/275444446' },
  { especie: 'Tira-vira', autor: 'Agustina Medina, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/256342499' },
  { especie: 'Traíra', autor: 'Pedro Silva, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/57061502' },
  { especie: 'Trairão', autor: 'facundo cortondo, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/103476812' },
  { especie: 'Truta arco-íris', autor: 'Mike Heine, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/286654424' },
  { especie: 'Tuvira', autor: 'Lucas Mantelo Cruz, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/245624950' },
  { especie: 'Xerelete', autor: 'Josiah Londerée, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/130934775' },
  { especie: 'Ximboré', autor: 'Lucas Mantelo Cruz, some rights reserved (CC BY)', licenca: 'CC-BY', pagina: 'https://www.inaturalist.org/observations/264011824' },
];
