/**
 * Fotos das espécies — **gerado** por `npm run photos:prepare`. Não edite à mão.
 *
 * São fotos de terceiros sob CC0, domínio público ou CC BY. O crédito ao autor é condição
 * da licença e vive em `creditos.ts`, que alimenta a tela de créditos do app.
 */

import type { ImageSourcePropType } from 'react-native';

export const FOTOS: Record<string, ImageSourcePropType> = {
  'abrotea': require('../../assets/especies/abrotea.jpg'),
  'anchova': require('../../assets/especies/anchova.jpg'),
  'bagre-africano': require('../../assets/especies/bagre-africano.jpg'),
  'bagre-amarelo': require('../../assets/especies/bagre-amarelo.jpg'),
  'bagre-americano': require('../../assets/especies/bagre-americano.jpg'),
  'bagre-branco': require('../../assets/especies/bagre-branco.jpg'),
  'baiacu': require('../../assets/especies/baiacu.jpg'),
  'biru': require('../../assets/especies/biru.jpg'),
  'black-bass': require('../../assets/especies/black-bass.jpg'),
  'cabrinha': require('../../assets/especies/cabrinha.jpg'),
  'cacao-anjo': require('../../assets/especies/cacao-anjo.jpg'),
  'cacao-bico-de-cristal': require('../../assets/especies/cacao-bico-de-cristal.jpg'),
  'cacao-bico-doce': require('../../assets/especies/cacao-bico-doce.jpg'),
  'cachara': require('../../assets/especies/cachara.jpg'),
  'caconete': require('../../assets/especies/caconete.jpg'),
  'cara': require('../../assets/especies/cara.jpg'),
  'cara-rabo-amarelo': require('../../assets/especies/cara-rabo-amarelo.jpg'),
  'carpa-cabeca-grande': require('../../assets/especies/carpa-cabeca-grande.jpg'),
  'carpa-capim': require('../../assets/especies/carpa-capim.jpg'),
  'carpa-colorida': require('../../assets/especies/carpa-colorida.jpg'),
  'carpa-espelho': require('../../assets/especies/carpa-espelho.jpg'),
  'carpa-hungara': require('../../assets/especies/carpa-hungara.jpg'),
  'carpa-prateada': require('../../assets/especies/carpa-prateada.jpg'),
  'cascudo': require('../../assets/especies/cascudo.jpg'),
  'castanha': require('../../assets/especies/castanha.jpg'),
  'chanchito': require('../../assets/especies/chanchito.jpg'),
  'chicharro': require('../../assets/especies/chicharro.jpg'),
  'congro': require('../../assets/especies/congro.jpg'),
  'corvina': require('../../assets/especies/corvina.jpg'),
  'dourado': require('../../assets/especies/dourado.jpg'),
  'esturjao': require('../../assets/especies/esturjao.jpg'),
  'grumata': require('../../assets/especies/grumata.jpg'),
  'guaivira': require('../../assets/especies/guaivira.jpg'),
  'joaninha': require('../../assets/especies/joaninha.jpg'),
  'jundia': require('../../assets/especies/jundia.jpg'),
  'kinguio': require('../../assets/especies/kinguio.jpg'),
  'lambari': require('../../assets/especies/lambari.jpg'),
  'lambari-cachorro': require('../../assets/especies/lambari-cachorro.jpg'),
  'lambari-rabo-vermelho': require('../../assets/especies/lambari-rabo-vermelho.jpg'),
  'linguado': require('../../assets/especies/linguado.jpg'),
  'mandi-amarelo': require('../../assets/especies/mandi-amarelo.jpg'),
  'maria-luiza': require('../../assets/especies/maria-luiza.jpg'),
  'marimba': require('../../assets/especies/marimba.jpg'),
  'miraguaia': require('../../assets/especies/miraguaia.jpg'),
  'mucum': require('../../assets/especies/mucum.jpg'),
  'pacu': require('../../assets/especies/pacu.jpg'),
  'pampo': require('../../assets/especies/pampo.jpg'),
  'papa-terra': require('../../assets/especies/papa-terra.jpg'),
  'papa-terra-listrado': require('../../assets/especies/papa-terra-listrado.jpg'),
  'parati': require('../../assets/especies/parati.jpg'),
  'peixe-espada': require('../../assets/especies/peixe-espada.jpg'),
  'peixe-galo': require('../../assets/especies/peixe-galo.jpg'),
  'peixe-rei-de-lagoa': require('../../assets/especies/peixe-rei-de-lagoa.jpg'),
  'peixe-rei-marinho': require('../../assets/especies/peixe-rei-marinho.jpg'),
  'pescada-branca': require('../../assets/especies/pescada-branca.jpg'),
  'pescada-olhuda': require('../../assets/especies/pescada-olhuda.jpg'),
  'pescadinha-real': require('../../assets/especies/pescadinha-real.jpg'),
  'piava': require('../../assets/especies/piava.jpg'),
  'pintachara': require('../../assets/especies/pintachara.jpg'),
  'pintado': require('../../assets/especies/pintado.jpg'),
  'pirapitinga': require('../../assets/especies/pirapitinga.jpg'),
  'raia-emplastro': require('../../assets/especies/raia-emplastro.jpg'),
  'raia-manteiga': require('../../assets/especies/raia-manteiga.jpg'),
  'raia-viola': require('../../assets/especies/raia-viola.jpg'),
  'robalo-flecha': require('../../assets/especies/robalo-flecha.jpg'),
  'robalo-peva': require('../../assets/especies/robalo-peva.jpg'),
  'savelha': require('../../assets/especies/savelha.jpg'),
  'sororoca': require('../../assets/especies/sororoca.jpg'),
  'tabarana': require('../../assets/especies/tabarana.jpg'),
  'tainha': require('../../assets/especies/tainha.jpg'),
  'tambacu': require('../../assets/especies/tambacu.jpg'),
  'tambaqui': require('../../assets/especies/tambaqui.jpg'),
  'tamboata': require('../../assets/especies/tamboata.jpg'),
  'tilapia': require('../../assets/especies/tilapia.jpg'),
  'tira-vira': require('../../assets/especies/tira-vira.jpg'),
  'traira': require('../../assets/especies/traira.jpg'),
  'trairao': require('../../assets/especies/trairao.jpg'),
  'truta-arco-iris': require('../../assets/especies/truta-arco-iris.jpg'),
  'tuvira': require('../../assets/especies/tuvira.jpg'),
  'xerelete': require('../../assets/especies/xerelete.jpg'),
  'ximbore': require('../../assets/especies/ximbore.jpg'),
};

/** `undefined` para espécie sem foto publicável — a tela decide o que desenhar no lugar. */
export function getFoto(speciesId: string): ImageSourcePropType | undefined {
  return FOTOS[speciesId];
}
