/**
 * CURADORIA MANUAL DO CATÁLOGO — a fonte humana da Etapa 0.
 *
 * O que vem daqui: nomes populares, apelidos regionais, raridade, faixas de tamanho, habitat,
 * curiosidade da ficha, espécies visualmente parecidas e os nomes das linhas de insígnia.
 * O que vem do FishBase (via build-catalog): coeficientes a/b e a conferência de nomenclatura.
 *
 * ┌─────────────────────────────────────────────────────────────────────────────────┐
 * │ ATENÇÃO — PRD seção 9.1                                                          │
 * │ As faixas de tamanho abaixo são ESTIMATIVAS regionais, não dado validado. Antes  │
 * │ de virar produção precisam de duas conferências:                                 │
 * │   1. nomenclatura científica — o build já faz, contra o FishBase;                │
 * │   2. validação de campo com pescadores da região — ninguém faz por você.         │
 * │ maxLengthCm não é o recorde mundial: é o maior exemplar que um amador do Sul     │
 * │ realisticamente pega. É ele que define o troféu (RN19), então um valor inflado   │
 * │ torna a insígnia inalcançável e um valor baixo a torna barata.                   │
 * └─────────────────────────────────────────────────────────────────────────────────┘
 */

import type { AlbumId, MeasureAxis, Rarity } from '../../src/catalog/types.ts';

/**
 * Nomes da linha de insígnia (PRD 11.6). Espécie lendária não tem bronze nem prata — a
 * primeira captura já entrega o ouro —, então esses dois são opcionais e o build força null.
 */
export interface CuratedBadges {
  bronze?: string;
  prata?: string;
  ouro: string;
  platina: string;
  diamante: string;
}

export interface CuratedSpecies {
  id: string;
  /** Em que álbuns a espécie aparece. A **posição** na grade vem de ALBUM_LAYOUT, abaixo. */
  albums: AlbumId[];
  commonName: string;
  aliases: string[];
  /** Nome aceito hoje. É o que aparece na ficha da espécie. */
  scientificName: string;
  /**
   * Nome sob o qual o FishBase ainda arquiva a espécie, quando difere do aceito.
   * Só para buscar coeficiente — nunca é exibido. Use quando uma revisão taxonômica recente
   * ainda não chegou ao snapshot, e registre o motivo em comentário.
   */
  fishbaseName?: string;
  /**
   * Congênere de quem emprestar a relação comprimento-peso, quando o FishBase não tem estudo
   * em TL para a espécie. Só para peixe de porte relevante — para lambari, não estimar peso é
   * melhor que estimar mal. O empréstimo é registrado no JSON e aparece na ficha.
   */
  fishbaseWeightProxy?: string;
  /**
   * Variedade, quando a carta é uma linhagem e não um táxon. Duas cartas podem compartilhar
   * `scientificName` desde que ambas declarem `variety` — é o que libera carpa-espelho e
   * carpa-colorida ao lado da carpa-húngara.
   */
  variety?: string;
  rarity: Rarity;
  /** Padrão `comprimento`. Só arraias verdadeiras usam `largura` (do disco). */
  measure?: MeasureAxis;
  minLengthCm: number;
  avgLengthCm: number;
  maxLengthCm: number;
  habitat: string[];
  fact: string;
  visuallySimilarTo: string[];
  /** Híbrido de pesqueiro: sem entrada no FishBase, nunca terá coeficiente próprio. */
  hybrid?: boolean;
  /** Ausente → o build aplica a regra de fallback do PRD 11.6 e marca como não curado. */
  badges?: CuratedBadges;
}

export const CURATED_SPECIES: CuratedSpecies[] = [
  // ───────────────────────────────────────────────────────── Álbum 1 — Pesqueiros do Sul
  {
    id: 'tilapia',
    albums: ['pesqueiros-sul', 'rios-acudes-sul'],
    commonName: 'Tilápia',
    aliases: ['tilápia-do-nilo', 'saint peter', 'tilápia-nilótica'],
    scientificName: 'Oreochromis niloticus',
    rarity: 'comum',
    minLengthCm: 12,
    avgLengthCm: 28,
    maxLengthCm: 55,
    habitat: ['pesqueiro', 'açude', 'rio'],
    fact: 'Originária da África, é o peixe mais estocado nos pesqueiros brasileiros e provavelmente o primeiro que você fisgou. Em ambiente natural do Sul é considerada invasora.',
    visuallySimilarTo: ['cara', 'tilapia-vermelha'],
    badges: {
      bronze: 'Oi, Tilápia',
      prata: 'De Novo?',
      ouro: 'É TILAAAAPIA',
      platina: 'Praga do Açude',
      diamante: 'Tilapocalipse',
    },
  },
  {
    id: 'carpa-hungara',
    albums: ['pesqueiros-sul', 'rios-acudes-sul'],
    commonName: 'Carpa-húngara',
    aliases: ['carpa', 'carpa-comum', 'carpa-escama'],
    scientificName: 'Cyprinus carpio',
    rarity: 'comum',
    minLengthCm: 20,
    avgLengthCm: 45,
    maxLengthCm: 90,
    habitat: ['pesqueiro', 'açude', 'rio'],
    fact: 'Come no fundo, revirando o lodo com a boca protrátil. É a briga mais pesada e mais lenta que um pesqueiro do Sul oferece.',
    visuallySimilarTo: ['carpa-capim', 'carpa-cabeca-grande', 'carpa-espelho', 'carpa-colorida', 'carpa-prateada', 'kinguio'],
    badges: {
      bronze: 'Bolinha de Massa',
      prata: 'Puxou Feio',
      ouro: 'Carpeiro',
      platina: 'Tanque Húngaro',
      diamante: 'Imperador do Fundo',
    },
  },
  {
    id: 'carpa-capim',
    albums: ['pesqueiros-sul'],
    commonName: 'Carpa-capim',
    aliases: ['carpa-herbívora', 'amur', 'carpa-do-capim'],
    scientificName: 'Ctenopharyngodon idella',
    rarity: 'incomum',
    minLengthCm: 25,
    avgLengthCm: 55,
    maxLengthCm: 110,
    habitat: ['pesqueiro', 'açude'],
    fact: 'Alimenta-se de vegetação e é estocada para controlar plantas aquáticas. Corpo alongado e cilíndrico, bem diferente da carpa-húngara.',
    visuallySimilarTo: ['carpa-hungara', 'carpa-cabeca-grande'],
  },
  {
    id: 'carpa-cabeca-grande',
    albums: ['pesqueiros-sul'],
    commonName: 'Carpa-cabeça-grande',
    aliases: ['carpa-cabeçuda', 'big head', 'carpa-prateada-cabeçuda'],
    scientificName: 'Hypophthalmichthys nobilis',
    rarity: 'incomum',
    minLengthCm: 25,
    avgLengthCm: 55,
    maxLengthCm: 110,
    habitat: ['pesqueiro', 'açude'],
    fact: 'Filtradora de plâncton, com a cabeça desproporcionalmente grande que lhe dá o nome. Raramente ataca isca — quando entra, costuma ser fisgada de raspão.',
    visuallySimilarTo: ['carpa-hungara', 'carpa-capim', 'carpa-prateada'],
  },
  {
    id: 'pacu',
    albums: ['pesqueiros-sul'],
    commonName: 'Pacu',
    aliases: ['pacu-caranha', 'caranha'],
    scientificName: 'Piaractus mesopotamicus',
    rarity: 'comum',
    minLengthCm: 15,
    avgLengthCm: 32,
    maxLengthCm: 50,
    habitat: ['pesqueiro', 'açude'],
    fact: 'Tem dentes molariformes que quebram sementes e caroços — e anzol mal escolhido. Nativo da bacia do Paraná, é presença certa em pesqueiro.',
    visuallySimilarTo: ['tambaqui', 'tambacu', 'pirapitinga'],
    badges: {
      bronze: 'Roubou a Massa',
      prata: 'Nadadeira Larga',
      ouro: 'Pacuzeiro',
      platina: 'Costela do Tanque',
      diamante: 'Chapa de Prata',
    },
  },
  {
    id: 'tambaqui',
    albums: ['pesqueiros-sul'],
    commonName: 'Tambaqui',
    aliases: ['tambaki'],
    scientificName: 'Colossoma macropomum',
    rarity: 'incomum',
    minLengthCm: 20,
    avgLengthCm: 45,
    maxLengthCm: 90,
    habitat: ['pesqueiro'],
    fact: 'Amazônico de origem, chega ao Sul apenas por estocagem — a água fria do inverno gaúcho limita a criação. É o maior caracídeo das Américas.',
    visuallySimilarTo: ['pacu', 'tambacu', 'pirapitinga'],
  },
  {
    id: 'tambacu',
    albums: ['pesqueiros-sul'],
    commonName: 'Tambacu',
    aliases: ['híbrido', 'tambacú'],
    scientificName: 'Piaractus mesopotamicus × Colossoma macropomum',
    rarity: 'incomum',
    minLengthCm: 20,
    avgLengthCm: 45,
    maxLengthCm: 90,
    habitat: ['pesqueiro'],
    fact: 'Híbrido de pacu com tambaqui, criado para juntar o crescimento rápido de um com a rusticidade do outro. Não existe na natureza — só em tanque.',
    visuallySimilarTo: ['pacu', 'tambaqui'],
    hybrid: true,
  },
  {
    id: 'bagre-africano',
    albums: ['pesqueiros-sul', 'rios-acudes-sul'],
    commonName: 'Bagre-africano',
    aliases: ['clarias', 'bagre-do-nilo', 'african'],
    scientificName: 'Clarias gariepinus',
    rarity: 'comum',
    minLengthCm: 20,
    avgLengthCm: 45,
    maxLengthCm: 100,
    habitat: ['pesqueiro', 'açude'],
    fact: 'Respira ar atmosférico e sobrevive horas fora d’água, o que o torna invasor perigoso quando escapa de tanque. Escorrega da mão como sabão.',
    visuallySimilarTo: ['jundia', 'bagre-branco', 'bagre-americano'],
    badges: {
      bronze: 'Que Isso?',
      prata: 'Melequento',
      ouro: 'Bagreiro',
      platina: 'Bigode de Aço',
      diamante: 'Sem Escama, Sem Medo',
    },
  },
  {
    id: 'jundia',
    albums: ['pesqueiros-sul', 'rios-acudes-sul'],
    commonName: 'Jundiá',
    aliases: ['jundiá-cinza', 'bagre-jundiá', 'jundia'],
    scientificName: 'Rhamdia quelen',
    rarity: 'comum',
    minLengthCm: 15,
    avgLengthCm: 28,
    maxLengthCm: 47,
    habitat: ['rio', 'açude', 'pesqueiro'],
    fact: 'O bagre nativo do Sul, de hábito noturno e presença em praticamente todo rio e açude gaúcho. Os ferrões peitorais doem por horas.',
    visuallySimilarTo: ['mandi-amarelo', 'bagre-africano', 'bagre-americano'],
    badges: {
      bronze: 'Escorregou',
      prata: 'Ferrão no Dedo',
      ouro: 'Jundiazeiro',
      platina: 'Bigode do Açude',
      diamante: 'Barba Longa',
    },
  },
  {
    id: 'traira',
    albums: ['pesqueiros-sul', 'rios-acudes-sul'],
    commonName: 'Traíra',
    aliases: ['lobó', 'tarairá', 'traira'],
    scientificName: 'Hoplias malabaricus',
    rarity: 'comum',
    minLengthCm: 15,
    avgLengthCm: 32,
    maxLengthCm: 60,
    habitat: ['açude', 'rio', 'pesqueiro'],
    fact: 'Predador de tocaia: fica parada junto ao barranco e ataca em explosão. A dentição é o motivo de todo pescador do Sul ter uma cicatriz para mostrar.',
    visuallySimilarTo: ['trairao'],
    badges: {
      bronze: 'Mordida Seca',
      prata: 'Cuidado com o Dedo',
      ouro: 'Pescador de Traíra',
      platina: 'Dona do Barranco',
      diamante: 'Traíra Não Perdoa',
    },
  },
  {
    id: 'pintado',
    albums: ['pesqueiros-sul'],
    commonName: 'Pintado',
    aliases: ['surubim', 'surubim-pintado'],
    scientificName: 'Pseudoplatystoma corruscans',
    rarity: 'raro',
    minLengthCm: 30,
    avgLengthCm: 60,
    maxLengthCm: 120,
    habitat: ['pesqueiro', 'rio'],
    fact: 'Marcado por pintas escuras arredondadas sobre fundo claro. Confundir com a cachara é o erro mais comum do álbum — nela o padrão vira faixas.',
    visuallySimilarTo: ['cachara', 'pintachara', 'surubim-do-uruguai'],
    badges: {
      bronze: 'Manchado',
      prata: 'Peso no Fundo',
      ouro: 'Pintadeiro',
      platina: 'Bigode Grande',
      diamante: 'Gigante de Couro',
    },
  },
  {
    id: 'cachara',
    albums: ['pesqueiros-sul'],
    commonName: 'Cachara',
    aliases: ['surubim-cachara', 'surubim'],
    scientificName: 'Pseudoplatystoma reticulatum',
    // Sem estudo comprimento-peso próprio no FishBase. O pintado é do mesmo gênero e tem
    // morfometria praticamente idêntica — é o empréstimo menos ruim, e vai declarado na ficha.
    fishbaseWeightProxy: 'Pseudoplatystoma corruscans',
    rarity: 'raro',
    minLengthCm: 30,
    avgLengthCm: 55,
    maxLengthCm: 90,
    habitat: ['pesqueiro', 'rio'],
    fact: 'O desenho é reticulado, formando faixas verticais que se conectam — não pintas soltas. Esse é o traço que a separa do pintado.',
    visuallySimilarTo: ['pintado', 'pintachara', 'surubim-do-uruguai'],
  },
  {
    id: 'pintachara',
    albums: ['pesqueiros-sul'],
    commonName: 'Pintachara',
    aliases: ['híbrido', 'pintachara'],
    scientificName: 'Pseudoplatystoma corruscans × Pseudoplatystoma reticulatum',
    rarity: 'raro',
    minLengthCm: 30,
    avgLengthCm: 58,
    maxLengthCm: 100,
    habitat: ['pesqueiro'],
    fact: 'Híbrido de pintado com cachara, com desenho intermediário que confunde até quem pesca há anos. Comum em pesqueiro, controverso em rio.',
    visuallySimilarTo: ['pintado', 'cachara'],
    hybrid: true,
  },
  {
    id: 'dourado',
    albums: ['pesqueiros-sul', 'rios-acudes-sul'],
    commonName: 'Dourado',
    aliases: ['dourado-do-rio', 'pirajuba', 'douradão'],
    scientificName: 'Salminus brasiliensis',
    rarity: 'raro',
    minLengthCm: 25,
    avgLengthCm: 55,
    maxLengthCm: 100,
    habitat: ['rio', 'pesqueiro'],
    fact: 'Chamado de tigre do rio pela briga: corre, salta e sacode a cabeça fora d’água. No rio Uruguai é a captura mais cobiçada do Sul.',
    visuallySimilarTo: ['tabarana'],
    badges: {
      bronze: 'Brilho na Água',
      prata: 'Pulou!',
      ouro: 'Caçador de Dourado',
      platina: 'Tigre do Rio',
      diamante: 'Ouro do Uruguai',
    },
  },
  {
    id: 'black-bass',
    albums: ['pesqueiros-sul', 'rios-acudes-sul'],
    commonName: 'Black bass',
    aliases: ['achigã', 'bass', 'black-bass'],
    scientificName: 'Micropterus salmoides',
    rarity: 'raro',
    minLengthCm: 15,
    avgLengthCm: 30,
    maxLengthCm: 55,
    habitat: ['açude', 'pesqueiro'],
    fact: 'Norte-americano introduzido no Sul, é o peixe que criou a pesca esportiva com isca artificial. Ataca de boca escancarada e pula para cuspir a isca.',
    visuallySimilarTo: [],
    badges: {
      bronze: 'Atacou a Isca',
      prata: 'Pulo do Bass',
      ouro: 'Basseiro',
      platina: 'Boca Grande',
      diamante: 'Lenda do Lago',
    },
  },
  {
    id: 'truta-arco-iris',
    albums: ['pesqueiros-sul'],
    commonName: 'Truta arco-íris',
    aliases: ['truta', 'trutinha'],
    scientificName: 'Oncorhynchus mykiss',
    rarity: 'incomum',
    minLengthCm: 18,
    avgLengthCm: 30,
    maxLengthCm: 60,
    habitat: ['serra', 'pesqueiro', 'rio'],
    fact: 'A carta característica da serra gaúcha e catarinense: São Francisco de Paula, Gramado, Canela, Urubici. Precisa de água fria e corrente para sobreviver.',
    visuallySimilarTo: [],
    badges: {
      bronze: 'Água Gelada',
      prata: 'Fisgou na Serra',
      ouro: 'Truteiro',
      platina: 'Arco-Íris Completo',
      diamante: 'Cristal de Urubici',
    },
  },

  // ────────────────────────────────────────────────────── Álbum 2 — Rios e açudes do Sul
  {
    id: 'lambari',
    albums: ['rios-acudes-sul'],
    commonName: 'Lambari',
    aliases: ['lambari-do-rabo-amarelo', 'tambiú', 'piaba'],
    scientificName: 'Astyanax lacustris',
    // A. altiparanae foi sinonimizada em A. lacustris; o snapshot v19.04 ainda mantém as duas
    // separadas, e é sob o nome antigo que estão os estudos e o comprimento máximo confiável.
    fishbaseName: 'Astyanax altiparanae',
    rarity: 'comum',
    minLengthCm: 5,
    avgLengthCm: 10,
    maxLengthCm: 16,
    habitat: ['rio', 'açude'],
    fact: 'O primeiro peixe de quase todo pescador brasileiro, e a isca viva mais usada para traíra e dourado. Anda em cardume e come qualquer coisa.',
    visuallySimilarTo: ['lambari-rabo-vermelho', 'lambari-cachorro'],
    badges: {
      bronze: 'Isca Viva',
      prata: 'Roubou a Massa',
      ouro: 'Zé do Lambari',
      platina: 'Cardume Inteiro',
      diamante: 'Fritada Histórica',
    },
  },
  {
    id: 'cara',
    albums: ['rios-acudes-sul'],
    commonName: 'Cará',
    aliases: ['acará', 'cará-comum', 'cara'],
    scientificName: 'Geophagus brasiliensis',
    rarity: 'comum',
    minLengthCm: 8,
    avgLengthCm: 16,
    maxLengthCm: 28,
    habitat: ['rio', 'açude', 'lagoa'],
    fact: 'Ciclídeo nativo com brilho azulado nas escamas. Peneira o substrato com a boca em busca de invertebrados — daí o nome do gênero, "comedor de terra".',
    visuallySimilarTo: ['tilapia', 'cara-rabo-amarelo', 'chanchito'],
    badges: {
      bronze: 'Peixinho Bonito',
      prata: 'Teimoso',
      ouro: 'Careiro',
      platina: 'Rei da Beirada',
      diamante: 'Azul de Açude',
    },
  },
  {
    id: 'mandi-amarelo',
    albums: ['rios-acudes-sul'],
    commonName: 'Mandi-amarelo',
    aliases: ['mandi', 'mandi-pintado', 'mandiuva'],
    scientificName: 'Pimelodus maculatus',
    rarity: 'comum',
    minLengthCm: 12,
    avgLengthCm: 25,
    maxLengthCm: 40,
    habitat: ['rio'],
    fact: 'Bagre de corpo amarelado com manchas escuras espalhadas. Anda em grupo e é o companheiro constante de quem pesca de fundo em rio do Sul.',
    visuallySimilarTo: ['jundia'],
    badges: {
      bronze: 'Amarelinho',
      prata: 'Espinho na Mão',
      ouro: 'Mandizeiro',
      platina: 'Bigode Amarelo',
      diamante: 'Ouro do Fundo',
    },
  },
  {
    id: 'piava',
    albums: ['rios-acudes-sul'],
    commonName: 'Piava',
    aliases: ['piapara', 'piau', 'piava-três-pintas'],
    scientificName: 'Megaleporinus obtusidens',
    rarity: 'comum',
    minLengthCm: 15,
    avgLengthCm: 30,
    maxLengthCm: 55,
    habitat: ['rio', 'açude'],
    fact: 'Tem manchas escuras arredondadas ao longo do corpo e boca pequena e dura, difícil de fisgar. O gênero era Leporinus até revisão taxonômica recente.',
    visuallySimilarTo: ['grumata', 'ximbore'],
    badges: {
      bronze: 'Mordida Rápida',
      prata: 'Boca Dura',
      ouro: 'Piaveiro',
      platina: 'Faixa Dourada',
      diamante: 'Correnteza Vencida',
    },
  },
  {
    id: 'grumata',
    albums: ['rios-acudes-sul'],
    commonName: 'Grumatã',
    aliases: ['curimba', 'curimbatá', 'curimatã', 'grumatã'],
    scientificName: 'Prochilodus lineatus',
    rarity: 'comum',
    minLengthCm: 18,
    avgLengthCm: 33,
    maxLengthCm: 60,
    habitat: ['rio'],
    fact: 'A boca em forma de ventosa, feita para raspar o fundo, é o que o separa da piava à primeira vista. Faz piracema em cardumes enormes.',
    visuallySimilarTo: ['piava', 'biru', 'ximbore'],
    badges: {
      bronze: 'Curimba ou Grumatã?',
      prata: 'Fisgado de Raspão',
      ouro: 'Grumatazeiro',
      platina: 'Cardume de Inverno',
      diamante: 'Senhor da Subida',
    },
  },
  {
    id: 'cascudo',
    albums: ['rios-acudes-sul'],
    commonName: 'Cascudo',
    aliases: ['acari', 'cascudo-preto', 'vieja'],
    scientificName: 'Hypostomus commersoni',
    rarity: 'comum',
    minLengthCm: 12,
    avgLengthCm: 28,
    maxLengthCm: 50,
    habitat: ['rio', 'açude'],
    fact: 'Coberto de placas ósseas e com boca de ventosa para raspar algas. Raramente morde anzol — quando acontece, é fisgada de fora.',
    visuallySimilarTo: ['cascudo-viola', 'tamboata'],
    badges: {
      bronze: 'Raspa-Vidro',
      prata: 'Couraça',
      ouro: 'Cascudeiro',
      platina: 'Armadura Completa',
      diamante: 'Fóssil Vivo',
    },
  },
  {
    id: 'peixe-rei-de-lagoa',
    albums: ['rios-acudes-sul'],
    commonName: 'Peixe-rei-de-lagoa',
    aliases: ['peixe-rei', 'pejerrey'],
    scientificName: 'Odontesthes bonariensis',
    rarity: 'incomum',
    minLengthCm: 12,
    avgLengthCm: 25,
    maxLengthCm: 45,
    habitat: ['lagoa', 'açude'],
    fact: 'Prateado e alongado, com uma faixa lateral brilhante. Prefere água fria — no Sul é pescaria de inverno nas lagoas.',
    visuallySimilarTo: ['peixe-rei-marinho'],
  },
  {
    id: 'pescada-branca',
    albums: ['rios-acudes-sul'],
    commonName: 'Pescada-branca',
    aliases: ['corvina-de-água-doce', 'pescada-do-piauí', 'pescada'],
    scientificName: 'Plagioscion squamosissimus',
    rarity: 'incomum',
    minLengthCm: 15,
    avgLengthCm: 30,
    maxLengthCm: 55,
    habitat: ['rio', 'açude'],
    fact: 'Parente de água doce da corvina marinha, introduzida em reservatórios de boa parte do país. Ataca isca artificial de meia-água ao entardecer.',
    visuallySimilarTo: ['corvina', 'pescada-olhuda', 'pescadinha-real'],
  },
  {
    id: 'trairao',
    albums: ['rios-acudes-sul'],
    commonName: 'Trairão',
    aliases: ['traíra-gigante', 'trairao'],
    scientificName: 'Hoplias lacerdae',
    // Mesmo gênero e mesmo plano corporal da traíra, que tem 23 estudos no FishBase.
    fishbaseWeightProxy: 'Hoplias malabaricus',
    rarity: 'raro',
    minLengthCm: 25,
    avgLengthCm: 45,
    maxLengthCm: 90,
    habitat: ['rio', 'açude'],
    fact: 'Versão grande da traíra, capaz de passar dos dez quilos. Vive em remansos profundos e engole isca do tamanho de um lambari adulto.',
    visuallySimilarTo: ['traira'],
    badges: {
      bronze: 'Isso Não é Traíra',
      prata: 'Levou a Isca',
      ouro: 'Trairãozeiro',
      platina: 'Boca de Balde',
      diamante: 'Monstro do Remanso',
    },
  },
  {
    id: 'tabarana',
    albums: ['rios-acudes-sul'],
    commonName: 'Tabarana',
    aliases: ['dourado-branco', 'tabarana'],
    scientificName: 'Salminus hilarii',
    rarity: 'raro',
    minLengthCm: 18,
    avgLengthCm: 32,
    maxLengthCm: 55,
    habitat: ['rio'],
    fact: 'Prima menor e mais clara do dourado, do mesmo gênero. Caça em água rasa e corrente, onde o dourado raramente entra.',
    visuallySimilarTo: ['dourado'],
    badges: {
      bronze: 'Parece Dourado',
      prata: 'Prata Viva',
      ouro: 'Tabaraneiro',
      platina: 'Flecha do Raso',
      diamante: 'Fantasma da Corredeira',
    },
  },
  {
    id: 'surubim-do-uruguai',
    albums: ['rios-acudes-sul'],
    commonName: 'Surubim-do-Uruguai',
    aliases: ['suruvi', 'surubim-pintado-do-uruguai'],
    scientificName: 'Steindachneridion scriptum',
    rarity: 'lendario',
    minLengthCm: 35,
    avgLengthCm: 60,
    maxLengthCm: 90,
    habitat: ['rio'],
    fact: 'Endêmico da bacia do Uruguai e ameaçado de extinção — capturá-lo é evento de uma vida. Se pegar, fotografe e devolva.',
    visuallySimilarTo: ['pintado', 'cachara'],
    badges: {
      ouro: 'Existe Mesmo',
      platina: 'Guardião do Uruguai',
      diamante: 'Mito do Rio',
    },
  },

  // ─────────────────────────────────────────────────────── Álbum 3 — Costa e lagoas do Sul
  {
    id: 'baiacu',
    albums: ['costa-sul'],
    commonName: 'Baiacu',
    aliases: ['baiacu-mirim', 'baiacu-pintado'],
    scientificName: 'Sphoeroides greeleyi',
    rarity: 'comum',
    minLengthCm: 8,
    avgLengthCm: 13,
    maxLengthCm: 18,
    habitat: ['litoral', 'estuário'],
    fact: 'Infla-se de água quando ameaçado e corta linha com os dentes fundidos em placa. Tóxico: não se come, e é o ladrão de isca mais odiado da praia.',
    visuallySimilarTo: [],
    badges: {
      bronze: 'Inchou',
      prata: 'De Novo Não',
      ouro: 'Baiacuzeiro',
      platina: 'Praga do Anzol',
      diamante: 'Bola de Espinho',
    },
  },
  {
    id: 'corvina',
    albums: ['costa-sul'],
    commonName: 'Corvina',
    aliases: ['corvina-branca', 'burriquete', 'corvinão'],
    scientificName: 'Micropogonias furnieri',
    rarity: 'comum',
    minLengthCm: 15,
    avgLengthCm: 32,
    maxLengthCm: 60,
    habitat: ['litoral', 'estuário', 'lagoa'],
    fact: 'Produz um ronco audível vibrando a bexiga natatória — dá para ouvir o cardume da praia. É o peixe de praia mais pescado do litoral gaúcho.',
    visuallySimilarTo: ['papa-terra', 'pescada-olhuda', 'miraguaia', 'pescada-branca', 'castanha'],
    badges: {
      bronze: 'Roncou',
      prata: 'Coro da Praia',
      ouro: 'Corvineiro',
      platina: 'Ronco de Cardume',
      diamante: 'Rainha da Arrebentação',
    },
  },
  {
    id: 'papa-terra',
    albums: ['costa-sul'],
    commonName: 'Papa-terra',
    aliases: ['betara', 'papa-terra-branco', 'perna-de-moça'],
    scientificName: 'Menticirrhus americanus',
    rarity: 'comum',
    minLengthCm: 12,
    avgLengthCm: 25,
    maxLengthCm: 45,
    habitat: ['litoral'],
    fact: 'Vive rente ao fundo na arrebentação, fuçando a areia com o barbilhão do queixo. Aparece junto com a corvina, mas tem corpo mais alongado.',
    visuallySimilarTo: ['corvina', 'papa-terra-listrado', 'maria-luiza', 'castanha'],
    badges: {
      bronze: 'Comeu no Fundo',
      prata: 'Areia na Linha',
      ouro: 'Betareiro',
      platina: 'Sentinela da Praia',
      diamante: 'Ouro da Beira',
    },
  },
  {
    id: 'bagre-branco',
    albums: ['costa-sul'],
    commonName: 'Bagre-branco',
    aliases: ['bagre', 'bagre-marinho', 'bagre-do-mar'],
    scientificName: 'Genidens barbus',
    rarity: 'comum',
    minLengthCm: 20,
    avgLengthCm: 38,
    maxLengthCm: 70,
    habitat: ['litoral', 'estuário'],
    fact: 'O macho carrega os ovos na boca até a eclosão, sem se alimentar. Os ferrões serrilhados justificam o respeito com que se retira o anzol.',
    visuallySimilarTo: ['bagre-africano', 'bagre-amarelo'],
  },
  {
    id: 'peixe-rei-marinho',
    albums: ['costa-sul'],
    commonName: 'Peixe-rei-marinho',
    aliases: ['peixe-rei', 'pejerrey-marinho'],
    scientificName: 'Odontesthes argentinensis',
    rarity: 'comum',
    minLengthCm: 12,
    avgLengthCm: 25,
    maxLengthCm: 45,
    habitat: ['litoral', 'lagoa'],
    fact: 'Anda em cardumes densos junto à arrebentação e é pescaria clássica de inverno no litoral do RS. A faixa prateada lateral brilha ao sol.',
    visuallySimilarTo: ['peixe-rei-de-lagoa'],
    badges: {
      bronze: 'Riscado de Prata',
      prata: 'Cardume Ligeiro',
      ouro: 'Peixe-Reizeiro',
      platina: 'Prata Corrida',
      diamante: 'Realeza da Lagoa',
    },
  },
  {
    id: 'tainha',
    albums: ['costa-sul'],
    commonName: 'Tainha',
    aliases: ['tainha-verdadeira', 'muge', 'parati-grande'],
    scientificName: 'Mugil liza',
    rarity: 'comum',
    minLengthCm: 20,
    avgLengthCm: 40,
    maxLengthCm: 70,
    habitat: ['litoral', 'estuário', 'lagoa'],
    fact: 'A safra de maio a julho move o litoral catarinense inteiro, com pesca de arrasto de praia e cardumes visíveis da areia. Come vegetal e detrito, quase nunca isca.',
    visuallySimilarTo: ['parati'],
    badges: {
      bronze: 'Lá Vem Ela',
      prata: 'Safra Aberta',
      ouro: 'Tainheiro',
      platina: 'Deu Tainha!',
      diamante: 'Dono da Safra',
    },
  },
  {
    id: 'pescada-olhuda',
    albums: ['costa-sul'],
    commonName: 'Pescada-olhuda',
    aliases: ['pescadinha', 'maria-mole', 'pescada'],
    scientificName: 'Cynoscion guatucupa',
    rarity: 'comum',
    minLengthCm: 15,
    avgLengthCm: 30,
    maxLengthCm: 55,
    habitat: ['litoral', 'estuário'],
    fact: 'Olho grande adaptado à caça em água turva e boca cheia de dentes caninos. Carne mole, que estraga rápido se não for gelada na hora.',
    visuallySimilarTo: ['corvina', 'pescada-branca', 'pescadinha-real'],
  },
  {
    id: 'marimba',
    albums: ['costa-sul'],
    commonName: 'Marimbá',
    aliases: ['sargo-de-dente', 'marimbau', 'marimba'],
    scientificName: 'Diplodus argenteus',
    // Sargo do mesmo gênero, corpo alto e comprimido igual, com 21 estudos limpos em TL.
    fishbaseWeightProxy: 'Diplodus sargus',
    rarity: 'incomum',
    minLengthCm: 12,
    avgLengthCm: 24,
    maxLengthCm: 40,
    habitat: ['litoral'],
    fact: 'Vive em costão rochoso e tem dentes incisivos que lembram os de um roedor, usados para arrancar mexilhão da pedra.',
    visuallySimilarTo: [],
  },
  {
    id: 'guaivira',
    albums: ['costa-sul'],
    commonName: 'Guaivira',
    aliases: ['tibiro', 'salteira', 'guaivira'],
    scientificName: 'Oligoplites saliens',
    rarity: 'incomum',
    minLengthCm: 15,
    avgLengthCm: 30,
    maxLengthCm: 50,
    habitat: ['litoral', 'estuário'],
    fact: 'Corpo comprimido e nadadeiras com espinhos livres, que ferem a mão desatenta. Caça em grupo na arrebentação e briga acima do peso.',
    visuallySimilarTo: ['anchova', 'pampo', 'xerelete'],
  },
  {
    id: 'peixe-espada',
    albums: ['costa-sul'],
    commonName: 'Peixe-espada',
    aliases: ['espada', 'lírio', 'peixe-espada-comum'],
    scientificName: 'Trichiurus lepturus',
    rarity: 'incomum',
    minLengthCm: 40,
    avgLengthCm: 75,
    maxLengthCm: 130,
    habitat: ['litoral', 'estuário'],
    fact: 'Corpo em fita prateada sem nadadeira caudal, com dentição que corta linha de aço fina. Sobe para a superfície à noite, atraído por luz.',
    visuallySimilarTo: [],
    badges: {
      bronze: 'Fita Prateada',
      prata: 'Dente por Dente',
      ouro: 'Espadeiro',
      platina: 'Lâmina Viva',
      diamante: 'Prata da Noite',
    },
  },
  {
    id: 'anchova',
    albums: ['costa-sul'],
    commonName: 'Anchova',
    aliases: ['enchova', 'anchova-azul', 'anchova-do-sul'],
    scientificName: 'Pomatomus saltatrix',
    rarity: 'incomum',
    minLengthCm: 20,
    avgLengthCm: 40,
    maxLengthCm: 80,
    habitat: ['litoral'],
    fact: 'Caça em cardume e mata mais do que come, deixando um rastro de peixe partido ao meio. Corta linha de nylon com facilidade — anzol de aço é obrigatório.',
    visuallySimilarTo: ['guaivira'],
    badges: {
      bronze: 'Cortou a Linha',
      prata: 'Dente Afiado',
      ouro: 'Anchoveiro',
      platina: 'Tesoura do Mar',
      diamante: 'Fúria Azul',
    },
  },
  {
    id: 'robalo-peva',
    albums: ['costa-sul'],
    commonName: 'Robalo-peva',
    aliases: ['robalo', 'camurim', 'robalo-chuchuca'],
    scientificName: 'Centropomus parallelus',
    rarity: 'raro',
    minLengthCm: 20,
    avgLengthCm: 40,
    maxLengthCm: 70,
    habitat: ['estuário', 'litoral'],
    fact: 'Menor e mais atarracado que o robalo-flecha, com preferência por mangue e água salobra. A linha lateral preta é a marca do gênero.',
    visuallySimilarTo: ['robalo-flecha'],
  },
  {
    id: 'robalo-flecha',
    albums: ['costa-sul'],
    commonName: 'Robalo-flecha',
    aliases: ['robalão', 'camurim-flecha', 'robalo'],
    scientificName: 'Centropomus undecimalis',
    rarity: 'raro',
    minLengthCm: 25,
    avgLengthCm: 50,
    maxLengthCm: 100,
    habitat: ['estuário', 'litoral'],
    fact: 'Corpo mais alongado e focinho mais afilado que o peva, e chega ao dobro do tamanho. Some no meio da estrutura no primeiro arranque.',
    visuallySimilarTo: ['robalo-peva'],
    badges: {
      bronze: 'Sombra no Mangue',
      prata: 'Quase Levou',
      ouro: 'Robaleiro',
      platina: 'Flecha Prateada',
      diamante: 'Fantasma do Costão',
    },
  },
  {
    id: 'linguado',
    albums: ['costa-sul'],
    commonName: 'Linguado',
    aliases: ['linguado-branco', 'solha', 'linguado-do-sul'],
    scientificName: 'Paralichthys orbignyanus',
    rarity: 'raro',
    minLengthCm: 20,
    avgLengthCm: 36,
    maxLengthCm: 62,
    habitat: ['litoral', 'estuário'],
    fact: 'Nasce simétrico e migra um olho para o outro lado do corpo ao crescer. Fica enterrado na areia esperando a presa passar por cima.',
    visuallySimilarTo: [],
    badges: {
      bronze: 'Achatado',
      prata: 'Camuflado',
      ouro: 'Linguadeiro',
      platina: 'Olho no Fundo',
      diamante: 'Tapete do Canal',
    },
  },
  {
    id: 'sororoca',
    albums: ['costa-sul'],
    commonName: 'Sororoca',
    aliases: ['serra', 'sororoca-serra', 'cavala-sororoca'],
    scientificName: 'Scomberomorus brasiliensis',
    // Os cinco estudos da sororoca estão em comprimento furcal, sem conversão para TL no
    // FishBase. A cavala é do mesmo gênero e tem estudo em TL.
    fishbaseWeightProxy: 'Scomberomorus cavalla',
    rarity: 'raro',
    minLengthCm: 25,
    avgLengthCm: 45,
    maxLengthCm: 80,
    habitat: ['litoral'],
    fact: 'Cavala de corpo riscado que cruza o litoral em cardume veloz, atrás de sardinha. Dentes de tesoura exigem encastoado de aço.',
    visuallySimilarTo: [],
  },
  {
    id: 'miraguaia',
    albums: ['costa-sul'],
    commonName: 'Miraguaia',
    aliases: ['miragaia', 'burro', 'miraguaia-do-sul'],
    scientificName: 'Pogonias courbina',
    // A população do Atlântico Sul foi separada de P. cromis em 2020. O snapshot v19.04 do
    // FishBase ainda arquiva tudo como cromis, então a busca de coeficiente usa o nome antigo.
    fishbaseName: 'Pogonias cromis',
    rarity: 'lendario',
    minLengthCm: 30,
    avgLengthCm: 70,
    maxLengthCm: 140,
    habitat: ['litoral', 'estuário'],
    fact: 'Pode passar de cinquenta quilos e tem dentes faringeanos capazes de triturar concha de marisco. Sobrepescada no Sul, virou captura de uma vez na vida.',
    visuallySimilarTo: ['corvina'],
    badges: {
      ouro: 'Bateu o Tambor',
      platina: 'Peso Morto',
      diamante: 'Lenda da Barra',
    },
  },
  // ══════════════════════════════════════ NOVAS — Álbum 1 (pesqueiros)
  {
    id: 'tilapia-vermelha',
    albums: ['pesqueiros-sul'],
    commonName: 'Tilápia-vermelha',
    aliases: ['saint peter vermelha', 'tilápia rosa', 'red tilápia'],
    scientificName: 'Oreochromis niloticus',
    variety: 'linhagem vermelha',
    rarity: 'comum',
    minLengthCm: 12,
    avgLengthCm: 28,
    maxLengthCm: 55,
    habitat: ['pesqueiro'],
    fact: 'Linhagem de coloração alaranjada selecionada para a mesa, porque a pele clara vale mais no filé. É a mesma espécie da tilápia comum — só a cor muda.',
    visuallySimilarTo: ['tilapia'],
    badges: {
      bronze: 'Que Cor é Essa?',
      prata: 'Rosinha',
      ouro: 'Tilápia de Gala',
      platina: 'Filé Nobre',
      diamante: 'Rainha do Tanque',
    },
  },
  {
    id: 'carpa-espelho',
    albums: ['pesqueiros-sul'],
    commonName: 'Carpa-espelho',
    aliases: ['carpa israel', 'carpa israelense', 'espelho', 'carpa sem escama'],
    scientificName: 'Cyprinus carpio',
    variety: 'espelho (linhagem israelense)',
    rarity: 'comum',
    minLengthCm: 20,
    avgLengthCm: 45,
    maxLengthCm: 90,
    habitat: ['pesqueiro', 'açude'],
    fact: 'Quase sem escamas, com algumas poucas grandes e brilhantes espalhadas pelo corpo — daí o nome. A linhagem chegou ao Brasil via Israel, e é por isso que meio mundo a chama de carpa israel.',
    visuallySimilarTo: ['carpa-hungara', 'carpa-colorida'],
    badges: {
      bronze: 'Cadê as Escamas?',
      prata: 'Espelhou',
      ouro: 'Carpa Israel',
      platina: 'Couro Liso',
      diamante: 'Espelho do Tanque',
    },
  },
  {
    id: 'carpa-colorida',
    albums: ['pesqueiros-sul'],
    commonName: 'Carpa-colorida',
    aliases: ['koi', 'carpa japonesa', 'nishikigoi', 'carpa laranja', 'carpa ornamental'],
    scientificName: 'Cyprinus carpio',
    variety: 'colorida (koi)',
    rarity: 'incomum',
    minLengthCm: 20,
    avgLengthCm: 40,
    maxLengthCm: 80,
    habitat: ['pesqueiro'],
    fact: 'Selecionada no Japão por mais de dois séculos só pela cor, e às vezes solta no pesqueiro para enfeitar. Fisgar uma dá aquela sensação de ter pescado o peixe errado.',
    visuallySimilarTo: ['carpa-hungara', 'carpa-espelho', 'kinguio'],
    badges: {
      bronze: 'Peguei o Enfeite',
      prata: 'Laranja Demais',
      ouro: 'Carpa Koi',
      platina: 'Jardim Japonês',
      diamante: 'Nishikigoi',
    },
  },
  {
    id: 'carpa-prateada',
    albums: ['pesqueiros-sul'],
    commonName: 'Carpa-prateada',
    aliases: ['carpa-prata', 'silver carp', 'carpa filtradora'],
    scientificName: 'Hypophthalmichthys molitrix',
    rarity: 'incomum',
    minLengthCm: 25,
    avgLengthCm: 50,
    maxLengthCm: 95,
    habitat: ['pesqueiro', 'açude'],
    fact: 'Filtradora como a cabeça-grande, mas de corpo prateado uniforme e cabeça menor. É famosa por saltar metros fora d’água quando assustada pelo motor de um barco.',
    visuallySimilarTo: ['carpa-cabeca-grande', 'carpa-hungara'],
    badges: {
      bronze: 'Pulou no Barco',
      prata: 'Prata Viva',
      ouro: 'Carpeiro de Prata',
      platina: 'Salto Alto',
      diamante: 'Chuva de Carpa',
    },
  },
  {
    id: 'pirapitinga',
    albums: ['pesqueiros-sul'],
    commonName: 'Pirapitinga',
    aliases: ['pacu-vermelho', 'caranha-vermelha'],
    scientificName: 'Piaractus brachypomus',
    rarity: 'incomum',
    minLengthCm: 20,
    avgLengthCm: 40,
    maxLengthCm: 75,
    habitat: ['pesqueiro'],
    fact: 'Prima amazônica do pacu, com a barriga alaranjada bem marcada quando jovem. Chega ao Sul só por estocagem de pesqueiro.',
    visuallySimilarTo: ['pacu', 'tambaqui'],
  },
  {
    id: 'bagre-americano',
    albums: ['pesqueiros-sul'],
    commonName: 'Bagre-americano',
    aliases: ['catfish', 'channel catfish', 'bagre-do-canal'],
    scientificName: 'Ictalurus punctatus',
    rarity: 'incomum',
    minLengthCm: 20,
    avgLengthCm: 45,
    maxLengthCm: 85,
    habitat: ['pesqueiro'],
    fact: 'Bagre norte-americano de cauda bifurcada e pintas escuras nos jovens, estocado em pesqueiro pela carne firme. A cauda em forquilha é o que o separa do jundiá e do africano.',
    visuallySimilarTo: ['bagre-africano', 'jundia'],
  },
  {
    id: 'esturjao',
    albums: ['pesqueiros-sul'],
    commonName: 'Esturjão',
    aliases: ['esturjão-russo', 'sturgeon', 'peixe-do-caviar'],
    scientificName: 'Acipenser gueldenstaedtii',
    rarity: 'raro',
    minLengthCm: 40,
    avgLengthCm: 80,
    maxLengthCm: 150,
    habitat: ['pesqueiro'],
    fact: 'Linhagem de peixe com mais de 200 milhões de anos, com placas ósseas no lugar de escamas e focinho de pá. No Sul existe por causa das fazendas de caviar, e alguns pesqueiros o estocam.',
    visuallySimilarTo: [],
    badges: {
      bronze: 'Isso é Peixe?',
      prata: 'Focinho de Pá',
      ouro: 'Caçador de Esturjão',
      platina: 'Fóssil na Linha',
      diamante: 'Senhor do Caviar',
    },
  },

  // ══════════════════════════════════════ NOVAS — Álbum 2 (rios e açudes)
  {
    id: 'lambari-rabo-vermelho',
    albums: ['rios-acudes-sul'],
    commonName: 'Lambari-do-rabo-vermelho',
    aliases: ['lambari-vermelho', 'tambiú-vermelho', 'piaba-vermelha'],
    scientificName: 'Astyanax fasciatus',
    rarity: 'comum',
    minLengthCm: 5,
    avgLengthCm: 10,
    maxLengthCm: 16,
    habitat: ['rio', 'açude'],
    fact: 'A nadadeira caudal avermelhada é o que o separa do lambari-do-rabo-amarelo, e os dois vivem lado a lado no mesmo cardume.',
    visuallySimilarTo: ['lambari', 'lambari-cachorro'],
  },
  {
    id: 'lambari-cachorro',
    albums: ['rios-acudes-sul'],
    commonName: 'Lambari-cachorro',
    aliases: ['tambicu', 'peixe-cachorro', 'lambari-guaçu', 'dentudo'],
    scientificName: 'Oligosarcus jenynsii',
    rarity: 'comum',
    minLengthCm: 8,
    avgLengthCm: 18,
    maxLengthCm: 30,
    habitat: ['rio', 'açude', 'lagoa'],
    fact: 'Lambari predador, de boca grande e dentes à mostra, que ataca isca artificial pequena. Comum em todo o RS e frequentemente confundido com um lambari comum grande.',
    visuallySimilarTo: ['lambari', 'lambari-rabo-vermelho'],
    badges: {
      bronze: 'Mostrou o Dente',
      prata: 'Lambari Bravo',
      ouro: 'Tambicu',
      platina: 'Dentuço do Açude',
      diamante: 'Cachorro Grande',
    },
  },
  {
    id: 'biru',
    albums: ['rios-acudes-sul'],
    commonName: 'Birú',
    aliases: ['voga', 'saguiru', 'birú-voga'],
    scientificName: 'Cyphocharax voga',
    rarity: 'comum',
    minLengthCm: 8,
    avgLengthCm: 16,
    maxLengthCm: 25,
    habitat: ['lagoa', 'rio', 'açude'],
    fact: 'Detritívoro de corpo prateado e boca pequena, abundantíssimo nas lagoas do RS. Raramente morde anzol, e é base da alimentação de traíra e dourado.',
    visuallySimilarTo: ['grumata'],
  },
  {
    id: 'cara-rabo-amarelo',
    albums: ['rios-acudes-sul'],
    commonName: 'Cará-do-rabo-amarelo',
    aliases: ['cará-amarelo', 'acará', 'cará-de-arroio'],
    scientificName: 'Gymnogeophagus rhabdotus',
    fishbaseWeightProxy: 'Geophagus brasiliensis',
    rarity: 'comum',
    minLengthCm: 5,
    avgLengthCm: 11,
    maxLengthCm: 16,
    habitat: ['rio', 'açude'],
    fact: 'Ciclídeo pequeno com faixa escura no flanco e cauda amarelada, típico dos arroios gaúchos. O gênero é quase todo endêmico do Sul e do Uruguai.',
    visuallySimilarTo: ['cara', 'chanchito'],
  },
  {
    id: 'chanchito',
    albums: ['rios-acudes-sul'],
    commonName: 'Chanchito',
    aliases: ['cará-listrado', 'acará-chanchito', 'cará'],
    scientificName: 'Australoheros facetus',
    rarity: 'incomum',
    minLengthCm: 6,
    avgLengthCm: 13,
    maxLengthCm: 20,
    habitat: ['rio', 'açude', 'lagoa'],
    fact: 'Ciclídeo de listras verticais escuras que ficam mais fortes quando ele está bravo, e ele fica bravo com facilidade. Defende a ninhada atacando o que passar.',
    visuallySimilarTo: ['cara', 'cara-rabo-amarelo'],
  },
  {
    id: 'joaninha',
    albums: ['rios-acudes-sul'],
    commonName: 'Joaninha',
    aliases: ['jacundá', 'peixe-sabão', 'crenicichla'],
    scientificName: 'Crenicichla lepidota',
    rarity: 'comum',
    minLengthCm: 6,
    avgLengthCm: 12,
    maxLengthCm: 20,
    habitat: ['rio', 'açude'],
    fact: 'Ciclídeo alongado de tocaia, com uma mancha redonda na base da cauda que parece um olho falso. Fica parada entre as pedras esperando um lambari desavisado.',
    visuallySimilarTo: [],
  },
  {
    id: 'mucum',
    albums: ['rios-acudes-sul'],
    commonName: 'Muçum',
    aliases: ['mussum', 'peixe-cobra', 'enguia-de-água-doce'],
    scientificName: 'Synbranchus marmoratus',
    rarity: 'incomum',
    minLengthCm: 20,
    avgLengthCm: 45,
    maxLengthCm: 90,
    habitat: ['açude', 'rio'],
    fact: 'Parece cobra, respira ar e consegue atravessar terra úmida entre um açude e outro. Nasce fêmea e vira macho ao envelhecer.',
    visuallySimilarTo: ['tuvira'],
    badges: {
      bronze: 'Isso é Cobra!',
      prata: 'Escorregou de Novo',
      ouro: 'Muçunzeiro',
      platina: 'Nó na Linha',
      diamante: 'Serpente do Açude',
    },
  },
  {
    id: 'tuvira',
    albums: ['rios-acudes-sul'],
    commonName: 'Tuvira',
    aliases: ['sarapó', 'peixe-faca', 'ituí'],
    scientificName: 'Gymnotus carapo',
    rarity: 'incomum',
    minLengthCm: 15,
    avgLengthCm: 35,
    maxLengthCm: 65,
    habitat: ['açude', 'rio'],
    fact: 'Nada para frente e para trás ondulando uma única nadadeira ventral, e se orienta por um campo elétrico fraco que ele mesmo gera. É a isca viva preferida para trairão.',
    visuallySimilarTo: ['mucum'],
  },
  {
    id: 'tamboata',
    albums: ['rios-acudes-sul'],
    commonName: 'Tamboatá',
    aliases: ['caborja', 'tamoatá', 'peixe-soldado'],
    scientificName: 'Hoplosternum littorale',
    rarity: 'incomum',
    minLengthCm: 8,
    avgLengthCm: 16,
    maxLengthCm: 25,
    habitat: ['açude', 'rio'],
    fact: 'Couraçado por duas fileiras de placas ósseas, respira ar pelo intestino e sobrevive em água podre onde nada mais vive. Constrói ninho de espuma na vegetação.',
    visuallySimilarTo: ['cascudo'],
  },
  {
    id: 'cascudo-viola',
    albums: ['rios-acudes-sul'],
    commonName: 'Cascudo-viola',
    aliases: ['viola', 'cascudo-chicote', 'loricária'],
    scientificName: 'Loricariichthys anus',
    rarity: 'incomum',
    minLengthCm: 15,
    avgLengthCm: 28,
    maxLengthCm: 45,
    habitat: ['lagoa', 'rio'],
    fact: 'Cascudo achatado e comprido, com cauda em chicote que pode ser metade do corpo. O macho carrega os ovos grudados no lábio inferior até eclodirem.',
    visuallySimilarTo: ['cascudo'],
  },
  {
    id: 'ximbore',
    albums: ['rios-acudes-sul'],
    commonName: 'Ximboré',
    aliases: ['voga', 'piau-ximboré', 'boga'],
    scientificName: 'Schizodon nasutus',
    rarity: 'incomum',
    minLengthCm: 12,
    avgLengthCm: 25,
    maxLengthCm: 38,
    habitat: ['rio', 'açude'],
    fact: 'Parente da piava com focinho mais pontudo e uma faixa escura contínua ao longo do corpo, em vez das manchas redondas. Come vegetal e é osso duro de fisgar.',
    visuallySimilarTo: ['piava', 'grumata'],
  },
  {
    id: 'kinguio',
    albums: ['rios-acudes-sul'],
    commonName: 'Kinguio',
    aliases: ['peixe-dourado', 'goldfish', 'carpa laranja', 'kinguim'],
    scientificName: 'Carassius auratus',
    rarity: 'raro',
    minLengthCm: 8,
    avgLengthCm: 18,
    maxLengthCm: 35,
    habitat: ['açude', 'lagoa'],
    fact: 'O peixinho-dourado de aquário, que solto em açude perde a cor de aquário e volta ao bronze escuro do ancestral selvagem. Espécie distinta da carpa, apesar do parentesco.',
    visuallySimilarTo: ['carpa-colorida', 'carpa-hungara'],
    badges: {
      bronze: 'Fugiu do Aquário',
      prata: 'Dourado de Vidro',
      ouro: 'Kinguieiro',
      platina: 'Sobrevivente do Açude',
      diamante: 'Peixinho de Ouro',
    },
  },

  // ══════════════════════════════════════ NOVAS — Álbum 3 (costa e lagoas)
  {
    id: 'castanha',
    albums: ['costa-sul'],
    commonName: 'Castanha',
    aliases: ['castanha-do-sul', 'corvina-castanha', 'castanheta'],
    scientificName: 'Umbrina canosai',
    rarity: 'comum',
    minLengthCm: 15,
    avgLengthCm: 27,
    maxLengthCm: 38,
    habitat: ['litoral'],
    fact: 'Sciaenídeo de corpo mais alto e escuro que a corvina, com listras oblíquas douradas. É uma das capturas mais frequentes da pesca de praia no inverno gaúcho.',
    visuallySimilarTo: ['corvina', 'papa-terra'],
  },
  {
    id: 'papa-terra-listrado',
    albums: ['costa-sul'],
    commonName: 'Papa-terra-listrado',
    aliases: ['betara-listrado', 'papa-terra-da-areia'],
    scientificName: 'Menticirrhus littoralis',
    rarity: 'incomum',
    minLengthCm: 12,
    avgLengthCm: 25,
    maxLengthCm: 45,
    habitat: ['litoral'],
    fact: 'Quase idêntico ao papa-terra comum, mas de corpo uniforme e sem as listras oblíquas — o que é irônico, dado o nome. Vive mais dentro da arrebentação que o parente.',
    visuallySimilarTo: ['papa-terra', 'maria-luiza'],
  },
  {
    id: 'maria-luiza',
    albums: ['costa-sul'],
    commonName: 'Maria-luiza',
    aliases: ['maria-luísa', 'cangoá', 'corvinota'],
    scientificName: 'Paralonchurus brasiliensis',
    rarity: 'comum',
    minLengthCm: 10,
    avgLengthCm: 20,
    maxLengthCm: 29,
    habitat: ['litoral'],
    fact: 'Pequeno sciaenídeo com uma barba de barbilhões curtos sob o queixo, usada para achar comida no fundo mole. Companhia constante de quem pesca corvina.',
    visuallySimilarTo: ['papa-terra', 'papa-terra-listrado'],
  },
  {
    id: 'pescadinha-real',
    albums: ['costa-sul'],
    commonName: 'Pescadinha-real',
    aliases: ['pescadinha', 'pescada-real', 'goete'],
    scientificName: 'Macrodon atricauda',
    rarity: 'comum',
    minLengthCm: 15,
    avgLengthCm: 28,
    maxLengthCm: 45,
    habitat: ['litoral', 'estuário'],
    fact: 'Tem dois caninos grandes e curvos na frente da boca, que a distinguem da pescada-olhuda. A população do Sul foi separada da do Nordeste como espécie própria em 2010.',
    visuallySimilarTo: ['pescada-olhuda', 'pescada-branca'],
  },
  {
    id: 'bagre-amarelo',
    albums: ['costa-sul'],
    commonName: 'Bagre-amarelo',
    aliases: ['bagre-guri', 'guri', 'bagre-do-estuário'],
    scientificName: 'Genidens genidens',
    rarity: 'comum',
    minLengthCm: 12,
    avgLengthCm: 25,
    maxLengthCm: 40,
    habitat: ['estuário', 'litoral'],
    fact: 'Bagre marinho menor e mais amarelado que o bagre-branco, dono absoluto da Lagoa dos Patos. Como o primo, o macho choca os ovos na boca.',
    visuallySimilarTo: ['bagre-branco'],
  },
  {
    id: 'parati',
    albums: ['costa-sul'],
    commonName: 'Parati',
    aliases: ['tainha-pequena', 'parati-olho-de-fogo', 'curimã'],
    scientificName: 'Mugil curema',
    rarity: 'comum',
    minLengthCm: 15,
    avgLengthCm: 28,
    maxLengthCm: 50,
    habitat: ['estuário', 'litoral', 'lagoa'],
    fact: 'Tainha menor, de olho com anel amarelo e corpo mais esguio, que fica no estuário o ano todo em vez de migrar. Muita gente chama qualquer tainha jovem de parati, mas é outra espécie.',
    visuallySimilarTo: ['tainha'],
  },
  {
    id: 'savelha',
    albums: ['costa-sul'],
    commonName: 'Savelha',
    aliases: ['sardinha-savelha', 'saveia', 'arenque-do-sul'],
    scientificName: 'Brevoortia pectinata',
    rarity: 'incomum',
    minLengthCm: 15,
    avgLengthCm: 25,
    maxLengthCm: 38,
    habitat: ['litoral', 'estuário'],
    fact: 'Anda em cardumes enormes rente à praia e é a isca preferida para anchova e cação. Escama solta com o toque e o corpo é achatado como o de uma sardinha grande.',
    visuallySimilarTo: [],
  },
  {
    id: 'cabrinha',
    albums: ['costa-sul'],
    commonName: 'Cabrinha',
    aliases: ['cabra', 'coió', 'peixe-voador-de-fundo'],
    scientificName: 'Prionotus punctatus',
    rarity: 'incomum',
    minLengthCm: 12,
    avgLengthCm: 25,
    maxLengthCm: 40,
    habitat: ['litoral'],
    fact: 'Tem nadadeiras peitorais enormes que abre como asas azuis, e três raios livres em cada lado que usa como pernas para caminhar no fundo. Ronca quando tirada da água.',
    visuallySimilarTo: [],
    badges: {
      bronze: 'Abriu as Asas',
      prata: 'Roncou na Mão',
      ouro: 'Cabrinheiro',
      platina: 'Asa Azul',
      diamante: 'Borboleta do Fundo',
    },
  },
  {
    id: 'abrotea',
    albums: ['costa-sul'],
    commonName: 'Abrótea',
    aliases: ['abrótea-do-sul', 'brótola', 'abrotia'],
    scientificName: 'Urophycis brasiliensis',
    rarity: 'incomum',
    minLengthCm: 15,
    avgLengthCm: 30,
    maxLengthCm: 50,
    habitat: ['litoral'],
    fact: 'Corpo mole e alongado, com a primeira nadadeira dorsal terminando num filamento longo e um barbilhão no queixo. Pescaria de inverno na praia gaúcha, quando a água esfria.',
    visuallySimilarTo: [],
  },
  {
    id: 'tira-vira',
    albums: ['costa-sul'],
    commonName: 'Tira-vira',
    aliases: ['tira-vira-do-sul', 'peixe-lagarto', 'pez palo'],
    scientificName: 'Percophis brasiliensis',
    rarity: 'incomum',
    minLengthCm: 18,
    avgLengthCm: 32,
    maxLengthCm: 50,
    habitat: ['litoral'],
    fact: 'Corpo alongado e achatado com boca enorme cheia de dentes finos, adaptado para emboscar de dentro da areia. Exclusivo do Atlântico Sul-ocidental — não existe em nenhum outro lugar.',
    visuallySimilarTo: [],
  },
  {
    id: 'chicharro',
    albums: ['costa-sul'],
    commonName: 'Chicharro',
    aliases: ['xixarro', 'carapau', 'chicharro-miúdo'],
    scientificName: 'Trachurus lathami',
    rarity: 'incomum',
    minLengthCm: 12,
    avgLengthCm: 22,
    maxLengthCm: 35,
    habitat: ['litoral'],
    fact: 'Carangídeo de cardume com uma quilha de escudos ósseos afiados ao longo da linha lateral, que corta a mão de quem segura errado. Come qualquer coisa pequena e brilhante.',
    visuallySimilarTo: ['xerelete'],
  },
  {
    id: 'peixe-galo',
    albums: ['costa-sul'],
    commonName: 'Peixe-galo',
    aliases: ['galo-de-penacho', 'galo', 'peixe-espelho'],
    scientificName: 'Selene setapinnis',
    rarity: 'incomum',
    minLengthCm: 15,
    avgLengthCm: 28,
    maxLengthCm: 50,
    habitat: ['litoral', 'estuário'],
    fact: 'Corpo tão achatado e prateado que parece uma folha de metal, com a testa quase vertical. De frente, quase desaparece na água.',
    visuallySimilarTo: [],
  },
  {
    id: 'xerelete',
    albums: ['costa-sul'],
    commonName: 'Xerelete',
    aliases: ['carapau', 'guarajuba', 'xaréu-azul'],
    scientificName: 'Caranx crysos',
    rarity: 'raro',
    minLengthCm: 20,
    avgLengthCm: 35,
    maxLengthCm: 60,
    habitat: ['litoral'],
    fact: 'Carangídeo veloz que caça em grupo perto de estrutura e briga muito acima do peso. No Sul aparece nos meses quentes, seguindo água mais azul.',
    visuallySimilarTo: ['chicharro', 'guaivira'],
  },
  {
    id: 'pampo',
    albums: ['costa-sul'],
    commonName: 'Pampo-do-sul',
    aliases: ['pampo', 'pompano', 'pampo-galhudo'],
    scientificName: 'Trachinotus marginatus',
    // Endêmico e pouco estudado: nenhum trabalho de peso. O pampo-do-atlântico é do mesmo
    // gênero e tem o mesmo corpo alto e comprimido.
    fishbaseWeightProxy: 'Trachinotus ovatus',
    rarity: 'incomum',
    minLengthCm: 12,
    avgLengthCm: 25,
    maxLengthCm: 40,
    habitat: ['litoral'],
    fact: 'Endêmico da zona de arrebentação do Sul do Brasil, Uruguai e Argentina — não ocorre em nenhum outro lugar do mundo. Nada na espuma, quase na areia, atrás de tatuíra.',
    visuallySimilarTo: ['guaivira'],
    badges: {
      bronze: 'Na Espuma',
      prata: 'Pegou na Tatuíra',
      ouro: 'Pampeiro',
      platina: 'Dono da Arrebentação',
      diamante: 'Só Existe Aqui',
    },
  },
  {
    id: 'congro',
    albums: ['costa-sul'],
    commonName: 'Congro',
    aliases: ['congro-rosa', 'enguia-do-mar', 'safio'],
    scientificName: 'Conger orbignianus',
    rarity: 'raro',
    minLengthCm: 30,
    avgLengthCm: 60,
    maxLengthCm: 100,
    habitat: ['litoral', 'estuário'],
    fact: 'Enguia marinha que passa o dia enfiada em fenda de pedra e sai à noite para caçar. Pega em molhe e trapiche, e dá um nó na linha antes de sair.',
    visuallySimilarTo: [],
  },
  {
    id: 'raia-emplastro',
    albums: ['costa-sul'],
    commonName: 'Raia-emplastro',
    aliases: ['raia-de-nariz-curto', 'emplastro', 'raia-santa'],
    scientificName: 'Sympterygia bonapartii',
    rarity: 'incomum',
    minLengthCm: 20,
    avgLengthCm: 40,
    maxLengthCm: 60,
    habitat: ['litoral', 'lagoa'],
    fact: 'Raia de corpo em losango e cauda fina, sem ferrão — o que assusta nela é só a aparência. Põe cápsulas córneas retangulares que dão na praia e viram o "saco de sereia".',
    visuallySimilarTo: ['raia-viola', 'raia-manteiga'],
  },
  {
    id: 'raia-manteiga',
    albums: ['costa-sul'],
    commonName: 'Raia-manteiga',
    aliases: ['ticonha', 'raia-águia', 'raia-de-fogo'],
    scientificName: 'Myliobatis goodei',
    rarity: 'raro',
    measure: 'largura',
    minLengthCm: 25,
    avgLengthCm: 50,
    maxLengthCm: 90,
    habitat: ['litoral', 'lagoa'],
    fact: 'Raia-águia de asas pontudas que literalmente voa debaixo d’água, com uma cabeça saliente à frente do disco. Tem ferrão na base da cauda — mede-se pela largura do disco.',
    visuallySimilarTo: ['raia-emplastro'],
  },
  {
    id: 'raia-viola',
    albums: ['costa-sul'],
    commonName: 'Raia-viola',
    aliases: ['cação-viola', 'viola', 'raia-guitarra'],
    scientificName: 'Pseudobatos horkelii',
    // Sem estudo próprio. A viola-do-pacífico é do mesmo gênero e do mesmo porte.
    fishbaseWeightProxy: 'Pseudobatos productus',
    rarity: 'raro',
    minLengthCm: 30,
    avgLengthCm: 70,
    maxLengthCm: 120,
    habitat: ['litoral'],
    fact: 'Metade raia, metade tubarão, com o corpo em forma de violão — não há como confundir. Está criticamente ameaçada e usa o litoral do RS como berçário: se pegar, devolva.',
    visuallySimilarTo: ['raia-emplastro', 'cacao-anjo'],
    badges: {
      bronze: 'Que Bicho É Esse?',
      prata: 'Meio Cação',
      ouro: 'Violeiro',
      platina: 'Guitarra do Sul',
      diamante: 'Devolvida à Água',
    },
  },
  {
    id: 'caconete',
    albums: ['costa-sul'],
    commonName: 'Caçonete',
    aliases: ['cação-bico-de-cristal', 'gatuso', 'cação-liso'],
    scientificName: 'Mustelus schmitti',
    rarity: 'incomum',
    minLengthCm: 30,
    avgLengthCm: 55,
    maxLengthCm: 85,
    habitat: ['litoral'],
    fact: 'Tubarão pequeno de dentes achatados feitos para triturar caranguejo, inofensivo para gente. Pele áspera de lixa e olhos verdes muito característicos.',
    visuallySimilarTo: ['cacao-bico-doce', 'cacao-bico-de-cristal'],
  },
  {
    id: 'cacao-bico-doce',
    albums: ['costa-sul'],
    commonName: 'Cação-bico-doce',
    aliases: ['frango-do-mar', 'cação', 'rabo-seco'],
    scientificName: 'Rhizoprionodon lalandii',
    rarity: 'incomum',
    minLengthCm: 30,
    avgLengthCm: 55,
    maxLengthCm: 90,
    habitat: ['litoral', 'estuário'],
    fact: 'O tubarãozinho que mais aparece na pesca de praia do Sul, de focinho longo e afilado. Nome de bico-doce porque o focinho é mole, não porque o bicho seja manso.',
    visuallySimilarTo: ['caconete', 'cacao-bico-de-cristal'],
    badges: {
      bronze: 'Peguei um Tubarão!',
      prata: 'Frango do Mar',
      ouro: 'Cacionista',
      platina: 'Lixa na Mão',
      diamante: 'Terror da Beira',
    },
  },
  {
    id: 'cacao-bico-de-cristal',
    albums: ['costa-sul'],
    commonName: 'Cação-bico-de-cristal',
    aliases: ['tubarão-sombreiro', 'cação-cambeva', 'tope'],
    scientificName: 'Galeorhinus galeus',
    rarity: 'raro',
    minLengthCm: 40,
    avgLengthCm: 80,
    maxLengthCm: 150,
    habitat: ['litoral'],
    fact: 'Tubarão migrador de grande porte, com a segunda dorsal quase do tamanho da anal. Sofreu colapso populacional no Sul e hoje é captura incomum e ameaçada.',
    visuallySimilarTo: ['caconete', 'cacao-bico-doce'],
  },
  {
    id: 'cacao-anjo',
    albums: ['costa-sul'],
    commonName: 'Cação-anjo',
    aliases: ['peixe-anjo', 'anjo', 'tubarão-anjo'],
    scientificName: 'Squatina guggenheim',
    // Sem estudo próprio. O anjo-europeu é do mesmo gênero e tem a mesma forma achatada.
    fishbaseWeightProxy: 'Squatina squatina',
    rarity: 'lendario',
    minLengthCm: 35,
    avgLengthCm: 70,
    maxLengthCm: 120,
    habitat: ['litoral'],
    fact: 'Tubarão achatado que passa a vida enterrado na areia esperando presa, com aparência de raia e mordida de tubarão. Criticamente ameaçado no Sul do Brasil — encontrar um é evento raro.',
    visuallySimilarTo: ['raia-viola'],
    badges: {
      ouro: 'Anjo na Areia',
      platina: 'Emboscada Perfeita',
      diamante: 'Anjo do Sul',
    },
  },
];

/**
 * ORDEM DAS CARTAS NA GRADE DE CADA ÁLBUM.
 *
 * Uma lista por álbum, na ordem em que as cartas aparecem. Agrupada por parentesco e por
 * ambiente, não alfabética: quem abre o álbum tem que ver as carpas juntas, os bagres juntos,
 * os cações juntos. Reordenar é mover uma linha; era por isso que a posição não podia continuar
 * como um número solto dentro de cada espécie.
 *
 * O build confere que esta lista e o campo `albums` de cada espécie dizem a mesma coisa.
 */
export const ALBUM_LAYOUT: Record<AlbumId, string[]> = {
  'pesqueiros-sul': [
    'tilapia',
    'tilapia-vermelha',
    'carpa-hungara',
    'carpa-espelho',
    'carpa-colorida',
    'carpa-capim',
    'carpa-cabeca-grande',
    'carpa-prateada',
    'pacu',
    'pirapitinga',
    'tambaqui',
    'tambacu',
    'bagre-africano',
    'bagre-americano',
    'jundia',
    'traira',
    'pintado',
    'cachara',
    'pintachara',
    'dourado',
    'black-bass',
    'truta-arco-iris',
    'esturjao',
  ],
  'rios-acudes-sul': [
    'lambari',
    'lambari-rabo-vermelho',
    'lambari-cachorro',
    'biru',
    'cara',
    'cara-rabo-amarelo',
    'chanchito',
    'joaninha',
    'traira',
    'trairao',
    'jundia',
    'mandi-amarelo',
    'mucum',
    'tuvira',
    'tamboata',
    'cascudo',
    'cascudo-viola',
    'piava',
    'ximbore',
    'grumata',
    'tilapia',
    'carpa-hungara',
    'kinguio',
    'bagre-africano',
    'black-bass',
    'peixe-rei-de-lagoa',
    'pescada-branca',
    'dourado',
    'tabarana',
    'surubim-do-uruguai',
  ],
  'costa-sul': [
    'baiacu',
    'corvina',
    'castanha',
    'papa-terra',
    'papa-terra-listrado',
    'maria-luiza',
    'pescada-olhuda',
    'pescadinha-real',
    'miraguaia',
    'bagre-branco',
    'bagre-amarelo',
    'peixe-rei-marinho',
    'tainha',
    'parati',
    'savelha',
    'marimba',
    'cabrinha',
    'abrotea',
    'tira-vira',
    'chicharro',
    'peixe-galo',
    'xerelete',
    'guaivira',
    'pampo',
    'anchova',
    'peixe-espada',
    'sororoca',
    'congro',
    'linguado',
    'robalo-peva',
    'robalo-flecha',
    'raia-emplastro',
    'raia-manteiga',
    'raia-viola',
    'caconete',
    'cacao-bico-doce',
    'cacao-bico-de-cristal',
    'cacao-anjo',
  ],
};
